### ISSUE TITLE
Deal with files that have a size of 0

### ISSUE THREAD

**Issue by ligi** [ligi/ipfs-api-kotlin#2]
```
Exception in thread "main" java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:59)
        at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
        at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:437)
        at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:418)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at kotlin.io.LinesSequence$iterator$1.hasNext(ReadWrite.kt:74)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:154)
        at kotlin.io.TextStreamsKt.readLines(ReadWrite.kt:37)
        at io.ipfs.kotlin.commands.Add.addGeneric(Add.kt:73)
        at io.ipfs.kotlin.commands.Add.directory(Add.kt:26)
        at io.ipfs.kotlin.commands.Add.directory$default(Add.kt:26)
        at kontinuum.WorkPackageProcessorKt.addIPFS(WorkPackageProcessor.kt:130)
        at kontinuum.WorkPackageProcessorKt.doIn(WorkPackageProcessor.kt:125)
        at kontinuum.WorkPackageProcessorKt.processWorkPackages(WorkPackageProcessor.kt:73)
        at kontinuum.MainKt.main(Main.kt:30)

```

**Comment by limuhai** [comment]
我也碰到这个问题了，有解决方案吗

**Comment by ligi** [comment]
I closed this issue because in the end I could deal with files that have a size of 0. Perhaps this error has another reason - can you reproduce?
